import { useEffect, useState } from 'react';
import { Clock3, FileSpreadsheet, Save, Settings2, UploadCloud } from 'lucide-react';
import toast from 'react-hot-toast';
import { hrAttendanceApi } from '../../api/hrAttendanceApi';
import { HrError, HrPageHeader, HrPageShell, HrStatusBadge, HrLoading } from '../../components/hr/HrUi';
import { Button } from '../../components/ui/Button';
import SEOHead from '../../components/SEOHead';

const initial = {
  headerRow: 2, employeeCodeColumn: 'B', employeeNameColumn: 'C', dateColumn: 'E', punchColumns: ['G', 'H', 'I', 'J'],
  checkInStart: '04:00', checkInEnd: '09:00', checkOutStart: '15:00', checkOutEnd: '20:00',
  defaultCheckIn: null, defaultCheckOut: null, standardCheckIn: '07:30', standardCheckOut: '16:30', graceMinutes: 10,
};
function shortTime(value, fallback) { const text = value || fallback || ''; return text.length >= 5 ? text.slice(0, 5) : text; }
function configToForm(value) {
  const merged = { ...initial, ...value };
  return { ...merged, checkInStart: shortTime(merged.checkInStart, initial.checkInStart), checkInEnd: shortTime(merged.checkInEnd, initial.checkInEnd), checkOutStart: shortTime(merged.checkOutStart, initial.checkOutStart), checkOutEnd: shortTime(merged.checkOutEnd, initial.checkOutEnd), defaultCheckIn: shortTime(merged.defaultCheckIn, ''), defaultCheckOut: shortTime(merged.defaultCheckOut, ''), standardCheckIn: shortTime(merged.standardCheckIn, initial.standardCheckIn), standardCheckOut: shortTime(merged.standardCheckOut, initial.standardCheckOut), punchColumns: (merged.punchColumns || initial.punchColumns).join(', ') };
}
function formToConfig(value) { return { ...value, headerRow: Number(value.headerRow), graceMinutes: Number(value.graceMinutes), punchColumns: value.punchColumns.split(',').map((item) => item.trim().toUpperCase()).filter(Boolean), defaultCheckIn: value.defaultCheckIn || null, defaultCheckOut: value.defaultCheckOut || null }; }
function Field({ label, field, value, setForm, type = 'text' }) { return <label className="block"><span className="mb-1 block text-sm font-medium text-gray-700">{label}</span><input type={type} value={value ?? ''} onChange={(event) => setForm((current) => ({ ...current, [field]: event.target.value }))} className="h-10 w-full rounded-lg border border-gray-300 px-3 text-sm outline-none focus:border-emerald-500 focus:ring-2 focus:ring-emerald-100" /></label>; }

export default function HrAttendance() {
  const [form, setForm] = useState(initial); const [imports, setImports] = useState({ content: [] }); const [selected, setSelected] = useState(null); const [preview, setPreview] = useState(null); const [file, setFile] = useState(null); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [uploading, setUploading] = useState(false); const [error, setError] = useState('');
  const reload = () => { setLoading(true); setError(''); Promise.all([hrAttendanceApi.getSettings(), hrAttendanceApi.listImports({ page: 0, size: 20 })]).then(([settings, result]) => { setForm(configToForm(settings)); setImports(result || { content: [] }); }).catch(() => setError('Không thể tải cấu hình hoặc lịch sử import chấm công.')).finally(() => setLoading(false)); };
  useEffect(() => { reload(); }, []);
  const save = async (event) => { event.preventDefault(); setSaving(true); try { const updated = await hrAttendanceApi.updateSettings(formToConfig(form)); setForm(configToForm(updated)); toast.success('Đã lưu cấu hình file chấm công.'); } catch (requestError) { toast.error(requestError?.response?.data?.message || 'Không thể lưu cấu hình.'); } finally { setSaving(false); } };
  const upload = async () => { if (!file) return toast.error('Hãy chọn file Excel trước.'); setUploading(true); try { const result = await hrAttendanceApi.upload(file); setSelected(result); setPreview(null); setFile(null); document.getElementById('attendance-file').value = ''; toast.success('Đã đọc file, xem kết quả ở bên dưới.'); reload(); } catch (requestError) { toast.error(requestError?.response?.data?.message || 'Không thể đọc file Excel.'); } finally { setUploading(false); } };
  const openPreview = async (item) => { setSelected(item); try { setPreview(await hrAttendanceApi.preview(item.id, { page: 0, size: 100 })); } catch { toast.error('Không thể tải bản xem trước.'); } };
  if (loading) return <HrPageShell><HrLoading label="Đang tải cấu hình chấm công..." /></HrPageShell>;
  if (error) return <HrPageShell><HrError message={error} onRetry={reload} /></HrPageShell>;
  return <HrPageShell>
    <SEOHead title="CFC Base | Chấm công" url="https://cfcbooking.io.vn/manager/hr/attendance" />
    <HrPageHeader title="Chấm công" description="Cấu hình định dạng file một lần, sau đó mỗi tháng chỉ cần tải file Excel lên để xem trước và lưu dữ liệu." actions={<Button type="button" variant="secondary" onClick={reload}>Tải lại</Button>} />
    <div className="grid gap-5 xl:grid-cols-[minmax(0,1fr)_380px]">
      <section className="rounded-xl border border-gray-200 bg-white p-5 shadow-sm"><div className="flex items-start gap-3"><div className="rounded-lg bg-emerald-50 p-2 text-emerald-700"><Settings2 className="h-5 w-5" /></div><div><h2 className="font-semibold text-gray-900">Cấu hình cột Excel</h2><p className="mt-1 text-sm text-gray-500">Nhập tên cột theo chữ Excel (A, B, C...). Không cần sửa code khi mẫu file thay đổi.</p></div></div>
        <form onSubmit={save} className="mt-5 grid gap-4 sm:grid-cols-2"><Field label="Dòng tiêu đề" field="headerRow" value={form.headerRow} setForm={setForm} type="number" /><Field label="Cột mã nhân viên" field="employeeCodeColumn" value={form.employeeCodeColumn} setForm={setForm} /><Field label="Cột họ tên" field="employeeNameColumn" value={form.employeeNameColumn} setForm={setForm} /><Field label="Cột ngày" field="dateColumn" value={form.dateColumn} setForm={setForm} /><div className="sm:col-span-2"><Field label="Các cột giờ chấm công (phân cách bằng dấu phẩy)" field="punchColumns" value={form.punchColumns} setForm={setForm} /></div><div className="sm:col-span-2 mt-2 border-t border-gray-100 pt-4"><p className="mb-3 text-sm font-semibold text-gray-800">Khung giờ tính công</p></div><Field label="Check in từ" field="checkInStart" value={form.checkInStart} setForm={setForm} type="time" /><Field label="Check in đến" field="checkInEnd" value={form.checkInEnd} setForm={setForm} type="time" /><Field label="Check out từ" field="checkOutStart" value={form.checkOutStart} setForm={setForm} type="time" /><Field label="Check out đến" field="checkOutEnd" value={form.checkOutEnd} setForm={setForm} type="time" /><Field label="Giờ mặc định Check in (tuỳ chọn)" field="defaultCheckIn" value={form.defaultCheckIn} setForm={setForm} type="time" /><Field label="Giờ mặc định Check out (tuỳ chọn)" field="defaultCheckOut" value={form.defaultCheckOut} setForm={setForm} type="time" /><div className="sm:col-span-2 mt-2 border-t border-gray-100 pt-4"><p className="mb-3 text-sm font-semibold text-gray-800">Tính đi trễ / về sớm</p></div><Field label="Giờ chuẩn vào" field="standardCheckIn" value={form.standardCheckIn} setForm={setForm} type="time" /><Field label="Giờ chuẩn ra" field="standardCheckOut" value={form.standardCheckOut} setForm={setForm} type="time" /><Field label="Miễn trừ (phút)" field="graceMinutes" value={form.graceMinutes} setForm={setForm} type="number" /><div className="sm:col-span-2"><Button type="submit" disabled={saving}><Save className="mr-1.5 h-4 w-4" />{saving ? 'Đang lưu...' : 'Lưu cấu hình'}</Button></div></form>
      </section>
      <section className="rounded-xl border border-gray-200 bg-white p-5 shadow-sm"><div className="flex items-start gap-3"><div className="rounded-lg bg-blue-50 p-2 text-blue-700"><UploadCloud className="h-5 w-5" /></div><div><h2 className="font-semibold text-gray-900">Import file tháng</h2><p className="mt-1 text-sm text-gray-500">Tối đa 15 MB · file .xlsx hoặc .xls</p></div></div><input id="attendance-file" type="file" accept=".xlsx,.xls" onChange={(event) => setFile(event.target.files?.[0] || null)} className="mt-5 block w-full text-sm" />{file && <p className="mt-2 truncate text-xs text-gray-500">{file.name}</p>}<Button type="button" onClick={upload} disabled={!file || uploading} className="mt-4 w-full"><FileSpreadsheet className="mr-1.5 h-4 w-4" />{uploading ? 'Đang đọc...' : 'Import & xem trước'}</Button><div className="mt-5 rounded-lg bg-slate-50 p-3 text-xs leading-5 text-gray-600"><p className="font-medium text-gray-800">Quy trình đề xuất</p><p>1. Lưu cấu hình đúng mẫu file hiện tại.</p><p>2. Import để kiểm tra mã nhân viên, ngày và giờ.</p><p>3. Chỉ dữ liệu hợp lệ mới được dùng cho bước tính công.</p></div></section>
    </div>
    <section className="mt-5 rounded-xl border border-gray-200 bg-white shadow-sm"><div className="border-b border-gray-100 px-5 py-4"><h2 className="font-semibold text-gray-900">Lịch sử file đã import</h2></div><div className="overflow-x-auto"><table className="min-w-[760px] w-full text-left text-sm"><thead className="bg-gray-50 text-xs uppercase tracking-wide text-gray-500"><tr><th className="px-4 py-3">File</th><th className="px-4 py-3">Tháng</th><th className="px-4 py-3">Tổng dòng</th><th className="px-4 py-3">Hợp lệ</th><th className="px-4 py-3">Lỗi</th><th className="px-4 py-3">Trạng thái</th><th className="px-4 py-3" /></tr></thead><tbody className="divide-y divide-gray-100">{imports.content?.map((item) => <tr key={item.id} className={selected?.id === item.id ? 'bg-emerald-50' : ''}><td className="px-4 py-3 font-medium">{item.fileName}</td><td className="px-4 py-3">{item.attendanceMonth || '—'}</td><td className="px-4 py-3">{item.totalRows}</td><td className="px-4 py-3 text-emerald-700">{item.validRows}</td><td className="px-4 py-3 text-red-600">{item.errorRows}</td><td className="px-4 py-3"><HrStatusBadge status={item.status} /></td><td className="px-4 py-3"><Button type="button" size="sm" variant="secondary" onClick={() => openPreview(item)}>Xem dòng</Button></td></tr>)}</tbody></table>{!imports.content?.length && <p className="p-8 text-center text-sm text-gray-500">Chưa có file chấm công nào.</p>}</div></section>
    {preview && <section className="mt-5 rounded-xl border border-gray-200 bg-white shadow-sm"><div className="flex items-center justify-between border-b border-gray-100 px-5 py-4"><div><h2 className="font-semibold text-gray-900">Xem trước: {preview.batch.fileName}</h2><p className="mt-1 text-sm text-gray-500">{preview.batch.validRows} dòng hợp lệ · {preview.batch.errorRows} dòng cần kiểm tra</p></div><Clock3 className="h-5 w-5 text-gray-400" /></div><div className="max-h-[480px] overflow-auto"><table className="min-w-[900px] w-full text-left text-sm"><thead className="sticky top-0 bg-gray-50 text-xs uppercase text-gray-500"><tr><th className="px-4 py-3">Dòng</th><th className="px-4 py-3">Mã NV</th><th className="px-4 py-3">Họ tên</th><th className="px-4 py-3">Ngày</th><th className="px-4 py-3">Check in</th><th className="px-4 py-3">Check out</th><th className="px-4 py-3">Kết quả</th></tr></thead><tbody className="divide-y divide-gray-100">{preview.rows.content.map((row) => <tr key={row.id}><td className="px-4 py-3">{row.sourceRowNumber}</td><td className="px-4 py-3 font-medium">{row.employeeCode}</td><td className="px-4 py-3">{row.employeeName || '—'}</td><td className="px-4 py-3">{row.workDate || '—'}</td><td className="px-4 py-3">{row.checkIn || '—'}</td><td className="px-4 py-3">{row.checkOut || '—'}</td><td className="px-4 py-3"><HrStatusBadge status={row.status} label={row.status === 'VALID' ? 'Hợp lệ' : row.errorMessage || row.status} /></td></tr>)}</tbody></table></div></section>}
  </HrPageShell>;
}
