import { mkdir, readdir, readFile, writeFile } from 'node:fs/promises';
import { resolve } from 'node:path';

const projectRoot = resolve(import.meta.dirname, '..');
const sourceDir = resolve(projectRoot, 'src/server');
const distDir = resolve(projectRoot, 'dist');

const sourceFiles = (await readdir(sourceDir))
  .filter((name) => /^\d+_.+\.js$/.test(name))
  .sort((left, right) => left.localeCompare(right));

if (sourceFiles.length === 0) {
  throw new Error('Không tìm thấy module server trong src/server.');
}

const modules = [];
for (const fileName of sourceFiles) {
  const source = await readFile(resolve(sourceDir, fileName), 'utf8');
  modules.push(`// ---- ${fileName} ----\n${source.trim()}\n`);
}

const manifest = await readFile(resolve(projectRoot, 'appsscript.json'), 'utf8');
JSON.parse(manifest);

await mkdir(distDir, { recursive: true });
await writeFile(
  resolve(distDir, 'Code.js'),
  `// Generated by scripts/build-server.mjs. Do not edit dist directly.\n'use strict';\n\n${modules.join('\n')}`,
  'utf8',
);
await writeFile(resolve(distDir, 'appsscript.json'), `${manifest.trim()}\n`, 'utf8');

process.stdout.write(`Built ${sourceFiles.length} server modules into dist/Code.js\n`);
