package com.booking.system.hr.importer;

public enum HrImportIssueCode {
    MISSING_REQUIRED_VALUE,
    INVALID_REQUIRED_VALUE,
    INVALID_OPTIONAL_VALUE,
    VALUE_NEEDS_REVIEW,
    NUMERIC_IDENTIFIER_COERCED,
    IDENTIFIER_FORMAT_NEEDS_REVIEW,
    INVALID_DATE,
    DATE_OUT_OF_RANGE,
    INVALID_NUMBER,
    NEGATIVE_NUMBER,
    DERIVED_TOTAL_MISMATCH,
    DERIVED_AGE_MISMATCH,
    UNKNOWN_GENDER,
    DUPLICATE_EMPLOYEE_CODE,
    EMPLOYEE_CODE_ALREADY_EXISTS,
    DUPLICATE_SOCIAL_INSURANCE_NUMBER,
    DUPLICATE_LEGACY_IDENTITY_NUMBER,
    SOURCE_ROW_ORDER_INVALID,
    MISSING_REVIEW_FIELD
}
